/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  safelist: [
    {
      pattern: /text-(xs|sm|base|lg|xl|2xl|3xl|4xl|5xl|6xl|7xl|8xl|9xl)/,
    },
    {
      pattern: /font-(thin|extralight|light|normal|medium|semibold|bold|extrabold|black)/,
    },
    {
      pattern: /tracking-(tighter|tight|normal|wide|wider|widest)/,
    },
    {
      pattern: /m(b|t|l|r|x|y)?-(0|1|2|3|4|5|6|7|8|9|10|11|12)/,
    },
    {
      pattern: /p(b|t|l|r|x|y)?-(0|1|2|3|4|5|6|7|8|9|10|11|12)/,
    },
    'min-h-screen',
    'bg-slate-50',
    'flex',
    'items-center',
    'justify-center',
    'max-w-md',
    'w-full',
    'bg-white',
    'rounded-2xl',
    'shadow-lg',
    'text-center',
    'space-y-6',
    'space-y-5',
    'relative',
    'block',
    'absolute',
    'left-3',
    'top-1/2',
    'transform',
    '-translate-y-1/2',
    'text-gray-400',
    'text-gray-600',
    'text-gray-700',
    'text-gray-800',
    'w-5',
    'h-5',
    'h-4',
    'w-4',
    'pl-10',
    'pr-4',
    'py-3',
    'py-3.5',
    'border',
    'border-gray-300',
    'rounded-lg',
    'focus:outline-none',
    'focus:border-blue-500',
    'focus:ring-2',
    'focus:ring-blue-100',
    'hover:bg-blue-700',
    'hover:bg-gray-50',
    'hover:text-blue-800',
    'hover:text-gray-800',
    'disabled:opacity-50',
    'disabled:cursor-not-allowed',
    'transition-all',
    'transition-colors',
    'text-blue-600',
    'text-red-600',
    'bg-blue-600',
    'text-white',
    'mr-2',
    'my-4',
    'my-6',
    'mb-2',
    'mb-5',
    'mb-6',
    'mb-8'
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
      },
    },
  },
  plugins: [],
}